language: php
php:
  - 7.1.0

install:
  - make install

before_script:
  - make update

job:
  include:
  - stage: test
    script:
      - ./vendor/bin/phpunit --bootstrap ./vendor/autoload.php --testdox ./lib/Test
